spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimaill_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        tx-service-group: fsp-tx-group
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    #password:
    port: 6379    #  默认端口号

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml   # 不配置默认就是这个目录
  global-config:
    db-config:
      id-type: auto # 配置主键自增

server:
  port: 8084


logging:
  level:
    com.bjc.gulimall.order.service.impl: debug

