spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.56.10
    #password:
    port: 6379    #  默认端口号
server:
  port: 12000


