spring:
  application:
    name: gulimall-third-party      # 注册中心服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   # 注册中心地址
    #alicloud:                         # OSS对象存储服务   配置单独抽取在Nacos中了
    #  access-key: LTAI4GHU。。。
    #  secret-key: nLLv4x0a2。。。
    #  oss:
    #    endpoint: oss-cn-hangzhou.aliyuncs.com

server:
  port: 9000
