server:
  port: 30000

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848         #  注册到注册中心
  redis:
    host: 192.168.56.10
    port: 6379
